### ISSUE TITLE
fix: Modifying a database column name

### ISSUE THREAD

**Issue by hoiae** [TRIP-SHOT/Server-Tripshot#3]
## 📌Feature Issue
> db컬럼 추가 및 컬럼명 수정
## 📝To-do
- [x] ratitude -> latitude로 오타 수정
- [x] shoot_date -> shot_date로 오타 수정
- [x] 조회api반환 값에 user의 nickname 추가
- [x] db에 location_name컬럼 추가

## ETC
>
